# 언어와 jdk 버전 지정
language: java
jdk:
  - openjdk11

# Travis CI를 어느 브랜치에 푸시될 때 수행 할 지 지정
branches:
  only:
    - main

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 지정된 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행된다.
# Travis CI에서 build한 jar파일을 S3에 업로드 하는 과정
# Travis 는 디렉토리 단위로만 업로드 가능
before_deploy:
  - zip -r amad-project *
  - mkdir -p deploy
  - mv amad-project.zip deploy/amad-project.zip

# S3로 파일 업로드 혹은 codedeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis 웹에서 설정한 환경 변수
    secret_access_key: $AWS_SECRET_KEY # Travis 웹에서 설정한 환경 변수
    bucket: amad-project-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy # 해당 위치의 파일들만 S3로 전송
    wait-until-deployed: true
    on:
      branch: main

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - lkdfj2212@gmail.com
